[package]
name = "askama"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.4.0"
askama = "0.12.1"
tokio = { version = "1.32.0", features = ["full"] }
